FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /workspace

ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1

EXPOSE 8080

CMD ["dotnet", "watch", "--project", "src/Auth.Presentation/Auth.Presentation.csproj", "run", "--no-launch-profile"]