services:
  notification-app:
    build: .
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start:dev
    depends_on:
      - notification-db

  notification-db:
    image: postgres:15-alpine
    env_file:
      - .env

