FROM node:22-alpine
WORKDIR /app

COPY prisma/ prisma/
COPY prisma.config.ts .
COPY package.json .
COPY pnpm-lock.yaml .
COPY tsconfig.json .
COPY tsconfig.build.json .

RUN corepack enable && corepack prepare pnpm@10 --activate
RUN pnpm install
RUN pnpm exec prisma generate

COPY src/ src/

CMD ["pnpm", "run", "start:dev"]
