FROM node:20-bookworm
WORKDIR /app

COPY prisma/ prisma/
COPY prisma.config.ts .
COPY package.json .
COPY tsconfig.json .
COPY tsconfig.build.json .

RUN npm install
RUN npx prisma generate

COPY src/ src/

CMD ["npm", "run", "start:dev"]
