include:
  - frontend/compose.yaml
  - services/auth/compose.yaml
  - services/chat/compose.yaml
  - services/gateway/compose.yaml
  - services/guild/compose.yaml
  - services/notification/compose.yaml
  - services/user/compose.yaml

services:
  cert-gen:
    container_name: cert-gen
    image: docker.io/alpine/curl
    user: "${FT_USERID:?FT_USERID not set}:${FT_GRPID:?FT_GRPID not set}"
    working_dir: /app
    volumes:
      - .:/app
    command: sh scripts/cert-gen.sh

  nginx:
    container_name: nginx
    image: docker.io/nginx:alpine
    network_mode: host
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      cert-gen:
        condition: service_completed_successfully
      gateway:
        condition: service_healthy
      frontend:
        condition: service_healthy

  rabbitmq:
    container_name: rabbitmq
    image: docker.io/rabbitmq:management-alpine
    user: "100:101"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./infra/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro,z
      - rabbitmq_data:/var/lib/rabbitmq:z
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
