services:
  guild:
    container_name: thing-guild
    image: guild-service
    build:
      context: ${PWD}/services/guild
    environment:
      RabbitMQ__Host: rabbitmq
      RabbitMQ__VirtualHost: /
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASS}
      Services__UserService: http://user:8080
      BackendConfiguration__BaseUrl: ${BASE_URL}
      BackendConfiguration__BaseApiUrl: ${BASE_API_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
