creation_rules:
  - path_regex: '^secrets/.*\.env\.crypt$'
    key_groups:
      - age:
          - age177x42mdywc7trn68g0nk35wy2306qstzsu2elgzp36f68cf5qe6s3jl7gu
          - age1lnm7u2w4hzcjrjxzg2p5x3rgythc9lmfyj67pa03zt7mhfr9symqdxkn23
          - age1gzenlllvttdf70xu3pr9y7pxfvu292e639eemczn5vuy3qcz69eqrzzgxa
          - age13lcxl50t8t7jf8crxprty2xkfhra5fg43sm5kle53unnxc56c55s4m2r9p
