// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationType string

const (
	NotificationTypeMention       NotificationType = "mention"
	NotificationTypeDm            NotificationType = "dm"
	NotificationTypeFriendRequest NotificationType = "friend_request"
	NotificationTypeGuildInvite   NotificationType = "guild_invite"
	NotificationTypeGuildWelcome  NotificationType = "guild_welcome"
	NotificationTypeIncomingCall  NotificationType = "incoming_call"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type Notification struct {
	ID          int64
	UserID      int64
	Type        NotificationType
	ActorID     *int64
	SourceID    *int64
	Payload     []byte
	ReadAt      pgtype.Timestamptz
	DismissedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type NotificationPreference struct {
	UserID     int64
	ScopeType  string
	ScopeID    int64
	Muted      bool
	MutedUntil pgtype.Timestamptz
}
