// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, user_id, type, actor_id, source_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, actor_id, source_id, payload, read_at, dismissed_at, created_at
`

type CreateNotificationParams struct {
	ID       int64
	UserID   int64
	Type     NotificationType
	ActorID  *int64
	SourceID *int64
	Payload  []byte
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.ActorID,
		arg.SourceID,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.ActorID,
		&i.SourceID,
		&i.Payload,
		&i.ReadAt,
		&i.DismissedAt,
		&i.CreatedAt,
	)
	return i, err
}
