// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isNotificationPreferenceMuted = `-- name: IsNotificationPreferenceMuted :one
SELECT EXISTS (
    SELECT 1
    FROM notification_preferences
    WHERE user_id = $1
        AND scope_type = $2
        AND scope_id = $3
        AND muted = true
        AND (muted_until IS NULL OR muted_until > NOW())
)
`

type IsNotificationPreferenceMutedParams struct {
	UserID    int64
	ScopeType string
	ScopeID   int64
}

func (q *Queries) IsNotificationPreferenceMuted(ctx context.Context, arg IsNotificationPreferenceMutedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isNotificationPreferenceMuted, arg.UserID, arg.ScopeType, arg.ScopeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listNotificationPreferences = `-- name: ListNotificationPreferences :many
SELECT user_id, scope_type, scope_id, muted, muted_until FROM notification_preferences
WHERE user_id = $1
`

func (q *Queries) ListNotificationPreferences(ctx context.Context, userID int64) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, listNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationPreference
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.UserID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Muted,
			&i.MutedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNotificationPreference = `-- name: RemoveNotificationPreference :execrows
DELETE FROM notification_preferences
WHERE user_id = $1 AND scope_type = $2 AND scope_id = $3
`

type RemoveNotificationPreferenceParams struct {
	UserID    int64
	ScopeType string
	ScopeID   int64
}

func (q *Queries) RemoveNotificationPreference(ctx context.Context, arg RemoveNotificationPreferenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeNotificationPreference, arg.UserID, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :one
INSERT INTO notification_preferences (user_id, scope_type, scope_id, muted, muted_until)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, scope_type, scope_id)
DO UPDATE SET
    muted = EXCLUDED.muted,
    muted_until = EXCLUDED.muted_until
RETURNING user_id, scope_type, scope_id, muted, muted_until
`

type UpsertNotificationPreferenceParams struct {
	UserID     int64
	ScopeType  string
	ScopeID    int64
	Muted      bool
	MutedUntil pgtype.Timestamptz
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreference,
		arg.UserID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Muted,
		arg.MutedUntil,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Muted,
		&i.MutedUntil,
	)
	return i, err
}
