services:
  gateway:
    restart: unless-stopped
    container_name: gateway
    image: gateway-service
    pull_policy: build
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
