services:
  gateway:
    restart: unless-stopped
    container_name: gateway
    image: gateway-service
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    volumes:
      - ./:/app
