services:
  gateway-service:
    restart: unless-stopped
    container_name: gateway-container
    image: gateway-image
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - "8090:8090"
    volumes:
      - ./:/app
