-- User Service — PostgreSQL schema
-- Owns: profiles, avatars, friend relationships, blocks, online status
--
-- ID policy: all BIGINT primary keys are Snowflake IDs generated by the service.
-- Never use DEFAULT / sequences for PK columns — the service is the sole authority.

CREATE TYPE user_status AS ENUM ('online', 'idle', 'dnd', 'offline');

CREATE TABLE users_profile (
    id              BIGINT      PRIMARY KEY,
    username        VARCHAR(32) UNIQUE NOT NULL,
    display_name    VARCHAR(64),
    avatar_url      VARCHAR(512),
    banner_url      VARCHAR(512),
    status          user_status NOT NULL DEFAULT 'offline',
    last_seen_at    TIMESTAMPTZ,
    bio             TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_users_profile_username_trgm     ON users_profile USING gin (username     gin_trgm_ops);
CREATE INDEX idx_users_profile_display_name_trgm ON users_profile USING gin (display_name gin_trgm_ops);

CREATE TYPE friendship_status AS ENUM ('pending', 'accepted', 'blocked');

CREATE TABLE friendships (
    id              BIGINT              PRIMARY KEY,
    requester_id    BIGINT              NOT NULL REFERENCES users_profile (id) ON DELETE CASCADE,
    addressee_id    BIGINT              NOT NULL REFERENCES users_profile (id) ON DELETE CASCADE,
    status          friendship_status   NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    CONSTRAINT no_self_friendship CHECK (requester_id != addressee_id)
);

CREATE UNIQUE INDEX unique_friendship_pair ON friendships (
    LEAST(requester_id, addressee_id),
    GREATEST(requester_id, addressee_id)
);

CREATE INDEX idx_friendships_requester         ON friendships (requester_id);
CREATE INDEX idx_friendships_addressee         ON friendships (addressee_id);
CREATE INDEX idx_friendships_pending_addressee ON friendships (addressee_id)
    WHERE status = 'pending';

CREATE TABLE user_blocks (
    blocker_id  BIGINT      NOT NULL REFERENCES users_profile (id) ON DELETE CASCADE,
    blocked_id  BIGINT      NOT NULL REFERENCES users_profile (id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (blocker_id, blocked_id),
    CONSTRAINT no_self_block CHECK (blocker_id != blocked_id)
);

CREATE INDEX idx_user_blocks_blocked ON user_blocks (blocked_id);

CREATE TYPE data_export_status AS ENUM ('pending', 'ready', 'failed');

CREATE TABLE data_exports (
    id          BIGINT              PRIMARY KEY,
    user_id     BIGINT              NOT NULL REFERENCES users_profile (id) ON DELETE CASCADE,
    status      data_export_status  NOT NULL DEFAULT 'pending',
    object_key  VARCHAR(512),
    expires_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX unique_pending_export_per_user ON data_exports (user_id)
    WHERE status = 'pending';

CREATE INDEX idx_data_exports_user ON data_exports (user_id, created_at DESC);
