FROM rust:1.88-bookworm AS dev
WORKDIR /app

RUN cargo install cargo-watch --locked

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo 'fn main() {}' > src/main.rs && \
    cargo build && \
    rm -f target/debug/deps/user_service*

COPY src/ src/

CMD ["cargo", "watch", "-x", "run"]
