FROM node:22-alpine
WORKDIR /app

RUN apk add --no-cache curl

COPY package.json package-lock.json ./
RUN npm ci

COPY tsconfig.json tsconfig.build.json ./

ENV PORT=8080
ENV NODE_ENV=development

EXPOSE 8080

CMD ["npm", "run", "start:dev"]
