FROM rust:latest
WORKDIR /app

RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo 'fn main() {}' > src/main.rs && \
    cargo build && \
    rm -f target/debug/deps/hello_world*

COPY src/ src/

CMD ["cargo", "watch", "-x", "run"]
