load('../../tiltlib.star', 'read_dotenv', 'detect_engine', 'run_flags', 'container_serve')

root_env = read_dotenv('../../.env')

DOCKER = detect_engine()
FLAGS  = run_flags(DOCKER)

local_resource(
    'user-db',
    serve_cmd=container_serve(DOCKER, FLAGS, 'user-db',
        '--network ft_transcendence ' +
        '--env-file .env ' +
        '-v user_db_data:/var/lib/postgresql/data ' +
        'docker.io/postgres:17-alpine'
    ),
    resource_deps=['dev-network'],
    labels=['user'],
)

local_resource(
    'user-migrate',
    cmd=DOCKER + ' build -t user-migrate-service-dev -f Dockerfile.migrate . && ' +
        DOCKER + ' run --rm --network ft_transcendence ' +
        '--env-file .env ' +
        '-e POSTGRES_HOST=user-db ' +
        '-e POSTGRES_PORT=5432 ' +
        'user-migrate-service-dev',
    resource_deps=['user-db'],
    labels=['user'],
)

local_resource(
    'user',
    cmd=DOCKER + ' build -t user-service-dev -f Dockerfile.dev .',
    serve_cmd=container_serve(DOCKER, FLAGS + '--init ', 'user',
        '--network ft_transcendence ' +
        '--env-file .env ' +
        '-e APP_ENV=development ' +
        '-e BASE_URL=' + root_env.get('BASE_URL', 'https://localhost:1443') + ' ' +
        '-e MINIO_ENDPOINT=http://minio:9000 ' +
        '-e MINIO_ACCESS_KEY=' + root_env.get('MINIO_ACCESS_KEY', 'minioadmin') + ' ' +
        '-e MINIO_SECRET_KEY=' + root_env.get('MINIO_SECRET_KEY', 'minioadmin') + ' ' +
        '-e MINIO_USER_BUCKET=' + root_env.get('MINIO_USER_BUCKET', 'user-avatars') + ' ' +
        '-e MINIO_EXPORTS_BUCKET=' + root_env.get('MINIO_EXPORTS_BUCKET', 'exports') + ' ' +
        '-e AUTH_INTERNAL_URL=' + root_env.get('AUTH_INTERNAL_URL', 'http://auth:8080') + ' ' +
        '-e GUILD_INTERNAL_URL=' + root_env.get('GUILD_INTERNAL_URL', 'http://guild:8080') + ' ' +
        '-e CHAT_INTERNAL_URL=' + root_env.get('CHAT_INTERNAL_URL', 'http://chat:8080') + ' ' +
        '-e NOTIFICATION_INTERNAL_URL=' + root_env.get('NOTIFICATION_INTERNAL_URL', 'http://notification:8080') + ' ' +
        '-e RABBITMQ_USER=' + root_env.get('RABBITMQ_USER', 'user') + ' ' +
        '-e RABBITMQ_PASS=' + root_env.get('RABBITMQ_PASS', 'password') + ' ' +
        '-e JWT_SECRET=' + root_env.get('JWT_SECRET', '') + ' ' +
        '-v $(pwd)/src:/app/src ' +
        '-v $(pwd)/package.json:/app/package.json ' +
        '-v $(pwd)/tsconfig.json:/app/tsconfig.json ' +
        '-v $(pwd)/tsconfig.build.json:/app/tsconfig.build.json ' +
        'user-service-dev npm run start:dev'
    ),
    deps=['Dockerfile.dev', 'Dockerfile', 'package.json', 'tsconfig.json', 'tsconfig.build.json'],
    resource_deps=['user-db', 'user-migrate'],
    labels=['user'],
)
