load('../../tiltlib.star', 'read_dotenv', 'detect_engine', 'run_flags', 'container_serve')

root_env = read_dotenv('../../.env')
DOCKER = detect_engine()
FLAGS  = run_flags(DOCKER)
MQ_USER = root_env.get('RABBITMQ_USER', 'guest')
MQ_PASS = root_env.get('RABBITMQ_PASS', 'guest')

local_resource(
    'user-db',
    serve_cmd=container_serve(DOCKER, FLAGS, 'user-db',
        '--network ft_transcendence ' +
        '--env-file .env ' +
        '-v user_db_data:/var/lib/postgresql/data ' +
        'docker.io/postgres:17-alpine'
    ),
    resource_deps=['dev-network'],
    labels=['user'],
)

local_resource(
    'user',
    cmd=DOCKER + ' build -t user-service -f Dockerfile.dev .',
    serve_cmd=container_serve(DOCKER, FLAGS + '--init ', 'user',
        '--network ft_transcendence ' +
        '--env-file .env ' +
        '-e APP_ENV=development ' +
        '-e RABBITMQ_HOST=rabbitmq ' +
        '-e RABBITMQ_PORT=5672 ' +
        '-e RABBITMQ_USERNAME=' + MQ_USER + ' ' +
        '-e RABBITMQ_PASSWORD=' + MQ_PASS + ' ' +
        '-e RABBITMQ_VHOST=/ ' +
        '-v $(pwd)/src:/app/src ' +
        'user-service cargo watch --poll -x run'
    ),
    deps=['Dockerfile.dev', 'Cargo.toml', 'Cargo.lock'],
    resource_deps=['user-db', 'rabbitmq'],
    labels=['user'],
)
