-- User Service — PostgreSQL schema
-- Owns: profiles, avatars, friend relationships, blocks, online status
--
-- ID policy: all BIGINT primary keys are Snowflake IDs generated by the service.
-- Never use DEFAULT / sequences for PK columns — the service is the sole authority.

CREATE TYPE user_status AS ENUM ('online', 'idle', 'dnd', 'offline');

CREATE TABLE users_profile (
    id              BIGINT      PRIMARY KEY,   -- same Snowflake as users_auth.id
    username        VARCHAR(32) UNIQUE NOT NULL,
    display_name    VARCHAR(64),
    avatar_url      VARCHAR(512),
    banner_url      VARCHAR(512),
    status          user_status NOT NULL DEFAULT 'offline',
    -- last_seen_at is updated when status transitions to 'offline'
    -- used for "last seen X ago" display on offline users
    last_seen_at    TIMESTAMPTZ,
    bio             TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- trigram index for `GET /users/search?q=...` (ILIKE / similarity matching on
-- username and display_name). display_name is created with a humanized default
-- on registration and can later be customized by the user. pg_trgm is a contrib module shipped with
-- Postgres core, no third-party dependency.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_users_profile_username_trgm     ON users_profile USING gin (username     gin_trgm_ops);
CREATE INDEX idx_users_profile_display_name_trgm ON users_profile USING gin (display_name gin_trgm_ops);

-- -----------------------------------------------------------------------
-- Friend relationships
--
-- requester_id is the user who initiated the friend request (= JWT sub at
-- POST /friends). addressee_id is the target. The direction matters for UI
-- ("X wants to be your friend" only shows on the addressee's side).
--
-- Duplicate prevention is independent of who initiated: there can only be
-- one row for the pair {A, B} regardless of ordering. Enforced by an
-- expression unique index on (LEAST, GREATEST).
-- -----------------------------------------------------------------------

CREATE TYPE friendship_status AS ENUM ('pending', 'accepted', 'blocked');

CREATE TABLE friendships (
    id              BIGINT              PRIMARY KEY,
    requester_id    BIGINT              NOT NULL REFERENCES users_profile (id) ON DELETE CASCADE,
    addressee_id    BIGINT              NOT NULL REFERENCES users_profile (id) ON DELETE CASCADE,
    status          friendship_status   NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW(),

    CONSTRAINT no_self_friendship   CHECK (requester_id != addressee_id)
);

-- order-independent uniqueness: at most one row per unordered pair {A, B}
CREATE UNIQUE INDEX unique_friendship_pair ON friendships (
    LEAST(requester_id, addressee_id),
    GREATEST(requester_id, addressee_id)
);

CREATE INDEX idx_friendships_requester          ON friendships (requester_id);
CREATE INDEX idx_friendships_addressee          ON friendships (addressee_id);
-- hot path: "show pending friend requests I've received"
CREATE INDEX idx_friendships_pending_addressee  ON friendships (addressee_id)
    WHERE status = 'pending';

-- -----------------------------------------------------------------------
-- User blocks (unilateral — independent of friendship status)
--
-- A blocks B: blocker_id = A, blocked_id = B.
-- B is not notified. B can still send messages; the frontend filters them out.
-- Guild Service / Chat Service honour blocks by checking this table via HTTP.
-- -----------------------------------------------------------------------

CREATE TABLE user_blocks (
    blocker_id  BIGINT      NOT NULL REFERENCES users_profile (id) ON DELETE CASCADE,
    blocked_id  BIGINT      NOT NULL REFERENCES users_profile (id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (blocker_id, blocked_id),
    CONSTRAINT no_self_block CHECK (blocker_id != blocked_id)
);

-- fast check: "has user X blocked me?" (needed before sending a DM)
CREATE INDEX idx_user_blocks_blocked ON user_blocks (blocked_id);

-- -----------------------------------------------------------------------
-- GDPR data-export jobs
--
-- Backs POST /users/me/data-export (the aggregator). One row per requested
-- export. The aggregator fans out to every service's internal data-export
-- leg, stitches one JSON bundle, uploads it to the `exports` object-storage
-- bucket, and generates a presigned download URL published in data.export_ready.
--
-- status lifecycle: pending -> ready | failed
-- object_key / expires_at are populated once the bundle is stored (status = ready).
-- -----------------------------------------------------------------------

CREATE TYPE data_export_status AS ENUM ('pending', 'ready', 'failed');

CREATE TABLE data_exports (
    id          BIGINT              PRIMARY KEY,   -- Snowflake; also the export_id on the wire
    user_id     BIGINT              NOT NULL REFERENCES users_profile (id) ON DELETE CASCADE,
    status      data_export_status  NOT NULL DEFAULT 'pending',
    -- object-storage key of the stored bundle, e.g. 'exports/{user_id}/{id}.json'.
    -- NULL until the bundle is uploaded (status = ready).
    object_key  VARCHAR(512),
    -- expiry of the presigned download URL (SigV4 caps presigned lifetime at 7 days)
    expires_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

-- rate limit: at most one in-flight (pending) export per user
CREATE UNIQUE INDEX unique_pending_export_per_user ON data_exports (user_id)
    WHERE status = 'pending';

-- status polling / list a user's exports, newest first
CREATE INDEX idx_data_exports_user ON data_exports (user_id, created_at DESC);
