<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Auth.ArchitectureTests</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Carter"                     Version="10.0.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"    Version="17.12.0"/>
        <PackageReference Include="xunit"                     Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Auth.Domain\Auth.Domain.csproj"/>
        <ProjectReference Include="..\..\src\Auth.Application\Auth.Application.csproj"/>
        <ProjectReference Include="..\..\src\Auth.Infrastructure\Auth.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\src\Auth.Persistence\Auth.Persistence.csproj"/>
        <ProjectReference Include="..\..\src\Auth.Presentation\Auth.Presentation.csproj"/>
    </ItemGroup>

</Project>
