// <auto-generated />
using System;
using Auth.Persistence.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auth.Persistence.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260503143221_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Entities.AuthUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("auth_users", null, t =>
                        {
                            t.HasCheckConstraint("email_or_oauth", "(\n            (email IS NOT NULL AND password_hash IS NOT NULL)\n            OR (oauth_provider IS NOT NULL AND oauth_id IS NOT NULL)\n        )");
                        });
                });

            modelBuilder.Entity("Auth.Domain.Entities.AuthUser", b =>
                {
                    b.OwnsOne("Auth.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<long>("AuthUserId")
                                .HasColumnType("bigint");

                            b1.Property<bool>("IsVerified")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("email_verified");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.HasKey("AuthUserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("idx_users_auth_email")
                                .HasFilter("deleted_at IS NULL AND email IS NOT NULL");

                            b1.ToTable("auth_users");

                            b1.WithOwner()
                                .HasForeignKey("AuthUserId");
                        });

                    b.OwnsOne("Auth.Domain.ValueObjects.OAuthIdentity", "OAuthIdentity", b1 =>
                        {
                            b1.Property<long>("AuthUserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("oauth_id");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("oauth_provider");

                            b1.HasKey("AuthUserId");

                            b1.HasIndex("Provider", "Id")
                                .IsUnique()
                                .HasDatabaseName("idx_users_auth_oauth")
                                .HasFilter("deleted_at IS NULL AND oauth_provider IS NOT NULL");

                            b1.ToTable("auth_users");

                            b1.WithOwner()
                                .HasForeignKey("AuthUserId");
                        });

                    b.OwnsOne("Auth.Domain.ValueObjects.StoredRefreshToken", "RefreshToken", b1 =>
                        {
                            b1.Property<long>("AuthUserId")
                                .HasColumnType("bigint");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("refresh_token_expires_at");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("refresh_token_hash");

                            b1.Property<DateTimeOffset>("IssuedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("refresh_token_issued_at");

                            b1.Property<bool>("Revoked")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("refresh_token_revoked");

                            b1.HasKey("AuthUserId");

                            b1.HasIndex("Hash")
                                .HasDatabaseName("idx_users_auth_refresh_token")
                                .HasFilter("deleted_at IS NULL\n                        AND refresh_token_revoked = FALSE\n                        AND refresh_token_hash IS NOT NULL");

                            b1.ToTable("auth_users");

                            b1.WithOwner()
                                .HasForeignKey("AuthUserId");
                        });

                    b.Navigation("Email");

                    b.Navigation("OAuthIdentity");

                    b.Navigation("RefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
