name: notification ci

on:
  pull_request:
    paths-ignore:
      - 'services/notification/**'
      - '.github/workflows/notification-ci.yml'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "nothing to do here, zzz..."

  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - run: echo "nothing to do here, zzz..."
